# Generated by Django 4.2.29 on 2026-04-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='current_area',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
